name: Unit Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:


jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm run bootstrap
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
